spring:
  config:
    import: optional:file:.env

  datasource: 
    url: jdbc:mysql://localhost:3306/movie_db
    username: root
    password: admin1234
    driver-class-name: com.mysql.cj.jdbc.Driver 
  jpa: 
    hibernate: 
      ddl-auto: update # 또는 create, create-drop, none 
    show-sql: true # JPA가 생성하는 SQL을 콘솔에 출력 
    properties: 
      hibernate: 
        format_sql: true # SQL 포맷팅

tmdb:
  api-key: 2fa7dc9bd134ff95650334b8030a032d

logging: 
  level: 
    org: 
      hibernate: 
        SQL: DEBUG # 실행되는 SQL 쿼리 로깅 
        type: 
          descriptor: 
            sql: TRACE # SQL 파라미터 로깅 